"""empty message

Revision ID: 48cb24d6da0c
Revises: 55f06c828437
Create Date: 2017-03-10 00:03:22.316491

"""

# revision identifiers, used by Alembic.
revision = '48cb24d6da0c'
down_revision = '55f06c828437'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
