"""empty message

Revision ID: 5084fd7388ab
Revises: 48cb24d6da0c
Create Date: 2017-03-10 00:05:18.842376

"""

# revision identifiers, used by Alembic.
revision = '5084fd7388ab'
down_revision = '48cb24d6da0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen_', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_seen_')
    # ### end Alembic commands ###
