"""empty message

Revision ID: 69b764dfd001
Revises: 74077fd77c39
Create Date: 2017-03-09 23:58:54.420477

"""

# revision identifiers, used by Alembic.
revision = '69b764dfd001'
down_revision = '74077fd77c39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
