"""empty message

Revision ID: 8cc8b28a2554
Revises: 5084fd7388ab
Create Date: 2017-03-10 00:06:18.968028

"""

# revision identifiers, used by Alembic.
revision = '8cc8b28a2554'
down_revision = '5084fd7388ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_seen_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen_', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
