"""empty message

Revision ID: 97a60d8e33c0
Revises: d657c6f7f2af
Create Date: 2017-03-10 00:15:20.909422

"""

# revision identifiers, used by Alembic.
revision = '97a60d8e33c0'
down_revision = 'd657c6f7f2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
