"""empty message

Revision ID: d657c6f7f2af
Revises: d2c067cd6861
Create Date: 2017-03-10 00:09:16.335520

"""

# revision identifiers, used by Alembic.
revision = 'd657c6f7f2af'
down_revision = 'd2c067cd6861'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
